# ./docker-compose.yml
version: '3.7'
#maintainer: "THIAGO FREITAS <freitasvazthiago@gmail.com>"

### Networks Setup #############################################

networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.3.0/24
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.4.0/24

### Services Setup #############################################

services:

 ### NGINX Server #############################################

  # nginx:
  #   image: ${URL_NEXUS}/nginx:1.0
  #   volumes:
  #     - ${APPLICATION}:/var/www
  #     - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
  #     - ${NGINX_SITES_PATH}:/etc/nginx/conf.d/
  #   ports:
  #     - "${NGINX_HOST_HTTP_PORT}:80"0,
  #     - "${NGINX_HOST_HTTPS_PORT}:443"
  #   networks:
  #     - frontend
  #     - backend

  react:
    build:
      context: ${APPLICATION}react-list
    ports:
      - "3000:3000"
    volumes:
      - ${APPLICATION}/react-list:/usr/src/app
    networks:
      - frontend
      - backend
    restart: always

  python:
    build:
      context: ${APPLICATION}flask-back
    ports:
      - "5000:5000"
    volumes:
      - ${APPLICATION}/flask-back:/usr/src/app
    networks:
      - frontend
      - backend
    restart: always