# ./docker-compose.yml
version: '3.7'
#maintainer: "THIAGO FREITAS <freitasvazthiago@gmail.com>"

### Networks Setup #############################################

networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.3.0/24
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.4.0/24

### Services Setup #############################################

services:

  ### Workspace Utilities ######################################

  workspace:
    image:  ${HOST}/workspace:1.0
    volumes:
      - ${APPLICATION}:/var/www
      - ${WORKSPACE_XDEBUG}:/usr/local/etc/php/conf.d/xdebug.ini
      - ${WORKSPACE_CRONTAB}:/etc/cron.d
    ports:
      - "${WORKSPACE_SSH_PORT}:22"
    tty: true
    networks:
      - frontend
      - backend

 ### NGINX Server #############################################

  nginx:
    image: ${HOST}/nginx:1.0
    volumes:
      - ${APPLICATION}:/var/www
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
    ports:
      - "${NGINX_HOST_HTTPS_PORT}:443"
      - "3000:3000"
      - "8000:8000"
      - "8001:8001"
    # depends_on:
    networks:
      - frontend
      - backend
      
  ### TESTE #####################################################

  web:
    build:
      context: ./react
      args:
        - HOST=${HOST}
    volumes:
      - ${APPLICATION}:/var/www
      - ${WEB_SITE_AVAILABLE}:/etc/apache2/sites-available
    ports:
      - "${WEB_PORT}:80"
    networks:
      - frontend
      - backend