# URL
ARG HOST=${HOST}

# REPOSITORY IMAGE REACT
FROM bayesimpact/react-base

# FILE AUTHOR / MAINTEAINER
LABEL mainteainer="THIAGO FREITAS <freitasvazthiago@gmail.com>"

# DELETE xdebug.ini
# RUN npm start